<?php

// autoload.php @generated by Composer

require_once __DIR__ . '/composer' . '/autoload_real.php';

return ComposerAutoloaderInit6a4446a12dedecbc68f5ffa1158f32c8::getLoader();
echo 'online github';
